export const IMAGE_ZONES = [
  {
    id: 'shelves',
    number: '01',
    label: 'Shelves',
    title: '主题书单',
    description: '围绕离散、酷儿、香港记忆、迁徙与现代化等主题整理的阅读路径。',
    action: '打开书单',
    href: '#shelves',
    x: 38, y: 45, w: 36, h: 28,
  },
  {
    id: 'programme',
    number: '02',
    label: 'Programme',
    title: '近期活动',
    description: '放映、读书会、讲座与小型文化聚会——查看近期活动与报名入口。',
    action: '查看活动',
    href: '#programme',
    x: 58, y: 55, w: 22, h: 20,
  },
  {
    id: 'screening-notes',
    number: '03',
    label: 'Screening Notes',
    title: '映后谈笔记',
    description: '从《敖鲁古雅》《秉爱》等放映后的对谈中，整理关于土地、迁徙、影像伦理与现代化的讨论。',
    action: '打开笔记',
    href: '#screening-notes',
    x: 74, y: 45, w: 24, h: 22,
  },
  {
    id: 'archive',
    number: '04',
    label: 'Archive',
    title: '过往活动档案',
    description: '记录曾经发生的放映、阅读、对话与现场痕迹。',
    action: '打开档案',
    href: '#archive',
    x: 14, y: 64, w: 22, h: 22,
  },
];
